### PR TITLE
fix(serve:ui): remove sudo, pass remaining cmdline args to serve

### PR DESCRIPTION
**Pull request by rob-solana**

### CODE REVIEW

**Comment by mvines** [comment]
Yeah we'll need an update around [here](https://github.com/solana-labs/solana/blob/7b35114c0f0e6f37b2a0ff85cf90a9102218ab33/net/remote/remote-node.sh#L118) to run on port 80 (with iptables, haproxy, or something else).

Also @rob-solana this project uses semantic-release so you'll need to format your commit title accordingly

**Comment by rob-solana** [comment]
https://github.com/solana-labs/solana/pull/3237

**Comment by rob-solana** [comment]
if we really want blockexplorer on port 80, we might consider using socat:
https://github.com/craSH/socat/blob/c20699fced66696e243d785fdfcd2a94cf11e4cc/EXAMPLES#L73

**Pull request merged**
