### PR TITLE
WIP : feature : rough implementation of redis object expiration (128k timeline/6h object timeout)

### PR DESCRIPTION
**Pull request by sunnygleason**
* Problem: redis overflowing memory on a 16GB fullnode with moderate load
* Solution: truncate objects (follow-up work will be more sustainable than dropping data)
* NOTE: Testing in progress

### CODE REVIEW

**Comment by sunnygleason** [comment]
@CriesofCarrots this is just an honorary PR review FYI, no obligation! :)

**Comment by mvines** [comment]
Cool.  Once this lands and is shipped, please update the version at https://github.com/solana-labs/solana/blob/v0.15/net/remote/remote-node.sh#L134 and tomorrow we can watch for blockexplorer flatlines on the real testnet :)

**Comment by sunnygleason** [comment]
@mvines initial testing looks good FYI, merging now.

**Pull request merged**
