### PR TITLE
RFC: Bx2 validators panel

### PR DESCRIPTION
**Pull request by sunnygleason**
Problem:

* need a validators table displaying group membership w/ stake

Solution:

* implement a validators panel

TODO (in another PR):

* styling, improvement of minor components (entity link, help link)

### CODE REVIEW

**Comment by sunnygleason** [comment]
@CriesofCarrots honorary PR/FYI 🏆

**Comment by sunnygleason** [comment]
@mvines FYI, this has the validators overview page ready to go, let me know if it's good to merge and send down the styling pipeline

**Comment by mvines** [comment]
yep, r+

**Pull request merged**
