### PR TITLE
feat: add https proxy server

### PR DESCRIPTION
**Pull request by mvines**
We need TLS endpoints for the api server and the JSON RPC ports.   This is now accomplished by a local https->http proxy running on the node.  

Currently a self-signed certificate is used.  Deploying a real certificate is still TBD

### CODE REVIEW

**Comment by mvines** [comment]
@sunnygleason fyi

**Comment by sunnygleason** [comment]
> @sunnygleason fyi

LGTM! I tend to prefer nginx/etc for a proxy, but at this stage & traffic
level I can see the use in having a Pure Node JS Environment(TM). Thank
you for making this happen!

**Comment by mvines** [comment]
Cool yeah I figured that since there's a 1-1 here between the https proxy and the target http port, and both are running on the same instance that it didn't make sense to get fancy.   If the proxy is overloaded then so is the underlying validator rpc port or blockexplorer api port, and we've already lost

**Pull request merged**
