### PR TITLE
Update entry.id to entry.hash

### PR DESCRIPTION
**Pull request by CriesofCarrots**
To catch up with solana core, need to update entry.id to entry.hash, renamed here: https://github.com/solana-labs/solana/commit/7c4473e0aabcd4e781f092146f1d7ec2967ace33

### CODE REVIEW

**Comment by sunnygleason** [comment]
@CriesofCarrots this makes sense! Should we change the corresponding "block" code so that https://github.com/solana-labs/blockexplorer/pull/34/files#diff-b45149d324de4d1fa7fa37391185799aL72 matches as well?

Thank you for keeping an eye on this, I appreciate it!

**Comment by CriesofCarrots** [comment]
Yes, we probably should. I'll go ahead and change that on the solana side in blockstream.

**Comment by CriesofCarrots** [comment]
Ugh, sorry, I forgot semantic-release.

**Pull request merged**
