### PR TITLE
Add updated layout for v2

### PR DESCRIPTION
**Pull request by devonbeard**
- Add updated header UI code
- Add updated nav bar UI code with active links
- Add initial responsive UI
- Add custom footer to the browse page
- Add icon fonts

### CODE REVIEW

**Comment by mvines** [comment]
@devonbeard - looks like CI had some objections with `src/v2/Bx2Footer.jsx`, see https://travis-ci.org/solana-labs/blockexplorer/builds/549990741#L538-L546.  Would you be able to take a look?

**Comment by sbhargava** [comment]
@mvines , @devonbeard 's stepping off the project--is this PR still useful (noticed it hasn't been merged yet)? Can someone inhouse fix the failing test and merge conflicts or no?

**Comment by mvines** [comment]
No this PR isn't useful

**Comment by sunnygleason** [comment]
@devonbeard thank you anyway for the initial contribution, we appreciate your work on it!

**Comment by devonbeard** [comment]
Of course. Thanks Sunny!

On Mon, Jul 1, 2019 at 12:36 PM, Sunny Gleason <notifications@github.com> wrote:
@devonbeard [https://github.com/devonbeard] thank you anyway for the initial contribution, we appreciate your work on it!

**Pull request closed without merging**
