### PR TITLE
new v3 app and dashboard started

### PR DESCRIPTION
**Pull request by manuel-calavera**
PR incorporates v3 app structure and starts implementation of stats dashboard component in new design/layout.

It does NOT brake/change existent v1/v2 code. New app is separated and available under /v3 route. It was implemented in properly written React code (async api layers, divided by components, independent routing, etc) and using next js guidelines:
https://github.com/airbnb/javascript

### CODE REVIEW

**Comment by mvines** [comment]
oh please use semantic-release commit naming

**Comment by mvines** [comment]
v1 is the production version that we want to keep.  v2 is the new app, we don't need a v3 :)

**Comment by mvines** [comment]
ie, let's fold this into v2.  That probably means you need to break this up into smaller chunks.   For example bring in the eslint changes on their own and other tooling changes on their own

**Comment by sunnygleason** [comment]
@manuel-calavera for this first PR there definitely shouldn't be any changes to './api' directory, if you can stash those that would be great

**Comment by manuel-calavera** [comment]
@sunnygleason it is ./src/api which my axios module

**Comment by sunnygleason** [comment]
> ie, let's fold this into v2. That probably means you need to break this up into smaller chunks. For example bring in the eslint changes on their own and other tooling changes on their own

+1 we shouldn't change eslint as part of a refactor because CI runs "yarn lint" and so many files are affected by re-pretty printing.

This PR should have a few files changed as possible.

**Comment by manuel-calavera** [comment]
@mvines ok. will close this one then

**Comment by mvines** [comment]
Thank you

**Comment by sunnygleason** [comment]
@manuel-calavera I like what you did with the component structure!

**Comment by manuel-calavera** [comment]
@sunnygleason glad you like it! i was afraid :)

**Pull request closed without merging**
